[2025-09-15T00:11:24.819+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-15T00:11:24.827+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: espn_news_pipeline.pull_api scheduled__2025-09-12T00:00:00+00:00 [queued]>
[2025-09-15T00:11:24.829+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: espn_news_pipeline.pull_api scheduled__2025-09-12T00:00:00+00:00 [queued]>
[2025-09-15T00:11:24.829+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-15T00:11:24.834+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): pull_api> on 2025-09-12 00:00:00+00:00
[2025-09-15T00:11:24.836+0000] {standard_task_runner.py:64} INFO - Started process 113 to run task
[2025-09-15T00:11:24.838+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'espn_news_pipeline', 'pull_api', 'scheduled__2025-09-12T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/news_pipeline.py', '--cfg-path', '/tmp/tmpkwbm1sai']
[2025-09-15T00:11:24.839+0000] {standard_task_runner.py:91} INFO - Job 3: Subtask pull_api
[2025-09-15T00:11:24.852+0000] {task_command.py:426} INFO - Running <TaskInstance: espn_news_pipeline.pull_api scheduled__2025-09-12T00:00:00+00:00 [running]> on host 6055f7975071
[2025-09-15T00:11:24.873+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='espn_news_pipeline' AIRFLOW_CTX_TASK_ID='pull_api' AIRFLOW_CTX_EXECUTION_DATE='2025-09-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-12T00:00:00+00:00'
[2025-09-15T00:11:24.873+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-15T00:11:24.878+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-15T00:11:24.878+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/news_pipeline.py", line 16, in run_etl
    from espn_etl.load_videos import load_insert_raw
  File "/opt/airflow/espn_etl/load_videos.py", line 4, in <module>
    from snowflake_connect import connect_to_schema
ModuleNotFoundError: No module named 'snowflake_connect'
[2025-09-15T00:11:24.880+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=espn_news_pipeline, task_id=pull_api, run_id=scheduled__2025-09-12T00:00:00+00:00, execution_date=20250912T000000, start_date=20250915T001124, end_date=20250915T001124
[2025-09-15T00:11:24.883+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 3 for task pull_api (No module named 'snowflake_connect'; 113)
[2025-09-15T00:11:24.895+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-09-15T00:11:24.902+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-15T00:11:24.904+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-09-16T07:12:29.689+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-16T07:12:29.700+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: espn_news_pipeline.pull_api scheduled__2025-09-12T00:00:00+00:00 [queued]>
[2025-09-16T07:12:29.702+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: espn_news_pipeline.pull_api scheduled__2025-09-12T00:00:00+00:00 [queued]>
[2025-09-16T07:12:29.702+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-16T07:12:29.708+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): pull_api> on 2025-09-12 00:00:00+00:00
[2025-09-16T07:12:29.713+0000] {standard_task_runner.py:64} INFO - Started process 118 to run task
[2025-09-16T07:12:29.726+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'espn_news_pipeline', 'pull_api', 'scheduled__2025-09-12T00:00:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/news_pipeline.py', '--cfg-path', '/tmp/tmpd3rvr5if']
[2025-09-16T07:12:29.732+0000] {standard_task_runner.py:91} INFO - Job 2: Subtask pull_api
[2025-09-16T07:12:29.768+0000] {task_command.py:426} INFO - Running <TaskInstance: espn_news_pipeline.pull_api scheduled__2025-09-12T00:00:00+00:00 [running]> on host d90780fea376
[2025-09-16T07:12:29.795+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='espn_news_pipeline' AIRFLOW_CTX_TASK_ID='pull_api' AIRFLOW_CTX_EXECUTION_DATE='2025-09-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-12T00:00:00+00:00'
[2025-09-16T07:12:29.796+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-16T07:12:31.092+0000] {logging_mixin.py:188} INFO - using account: ggjmket-vqb12267
[2025-09-16T07:12:31.092+0000] {connection.py:408} INFO - Snowflake Connector for Python Version: 3.11.0, Python Version: 3.11.9, Platform: Linux-6.10.14-linuxkit-aarch64-with-glibc2.36
[2025-09-16T07:12:31.092+0000] {connection.py:1258} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-09-16T07:12:32.962+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2025-09-16T07:12:32.966+0000] {logging_mixin.py:188} INFO - ctx: ('WBB71043', 'ACCOUNTADMIN', 'ESPN_WH', 'API_DATA_DB', 'RAW_JSON')
[2025-09-16T07:12:33.934+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2025-09-16T07:12:33.936+0000] {logging_mixin.py:188} INFO - working on basketball nba
[2025-09-16T07:12:34.070+0000] {logging_mixin.py:188} INFO - basketball/nba call successful
[2025-09-16T07:12:34.073+0000] {logging_mixin.py:188} INFO - working on basketball mens-college-basketball
[2025-09-16T07:12:34.237+0000] {logging_mixin.py:188} INFO - basketball/mens-college-basketball call successful
[2025-09-16T07:12:34.241+0000] {logging_mixin.py:188} INFO - working on football nfl
[2025-09-16T07:12:34.338+0000] {logging_mixin.py:188} INFO - football/nfl call successful
[2025-09-16T07:12:34.341+0000] {logging_mixin.py:188} INFO - working on football college-football
[2025-09-16T07:12:34.411+0000] {logging_mixin.py:188} INFO - football/college-football call successful
[2025-09-16T07:12:34.412+0000] {logging_mixin.py:188} INFO - working on baseball mlb
[2025-09-16T07:12:34.500+0000] {logging_mixin.py:188} INFO - baseball/mlb call successful
[2025-09-16T07:12:34.502+0000] {logging_mixin.py:188} INFO - working on hockey nhl
[2025-09-16T07:12:34.597+0000] {logging_mixin.py:188} INFO - hockey/nhl call successful
[2025-09-16T07:12:34.599+0000] {logging_mixin.py:188} INFO - working on soccer usa.1
[2025-09-16T07:12:34.705+0000] {logging_mixin.py:188} INFO - soccer/usa.1 call successful
[2025-09-16T07:12:34.707+0000] {logging_mixin.py:188} INFO - working on mma ufc
[2025-09-16T07:12:34.811+0000] {logging_mixin.py:188} INFO - mma/ufc call successful
[2025-09-16T07:12:34.813+0000] {logging_mixin.py:188} INFO - working on golf pga
[2025-09-16T07:12:34.903+0000] {logging_mixin.py:188} INFO - golf/pga call successful
[2025-09-16T07:12:34.905+0000] {logging_mixin.py:188} INFO - working on tennis atp
[2025-09-16T07:12:35.043+0000] {logging_mixin.py:188} INFO - tennis/atp call successful
[2025-09-16T07:12:37.311+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2025-09-16T07:12:38.005+0000] {cursor.py:1149} INFO - Number of results in first chunk: 5
[2025-09-16T07:12:38.006+0000] {connection.py:773} INFO - closed
[2025-09-16T07:12:38.064+0000] {connection.py:779} INFO - No async queries seem to be running, deleting session
[2025-09-16T07:12:38.447+0000] {logging_mixin.py:188} INFO - âœ… ETL finished
[2025-09-16T07:12:38.448+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-09-16T07:12:38.449+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-16T07:12:38.456+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=espn_news_pipeline, task_id=pull_api, run_id=scheduled__2025-09-12T00:00:00+00:00, execution_date=20250912T000000, start_date=20250916T071229, end_date=20250916T071238
[2025-09-16T07:12:38.511+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-09-16T07:12:38.520+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-09-16T07:12:38.522+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
