[2025-09-18T00:01:32.897+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-18T00:01:32.907+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: espn_news_pipeline.dbt_setup scheduled__2025-09-15T00:00:00+00:00 [queued]>
[2025-09-18T00:01:32.909+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: espn_news_pipeline.dbt_setup scheduled__2025-09-15T00:00:00+00:00 [queued]>
[2025-09-18T00:01:32.910+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-18T00:01:32.914+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_setup> on 2025-09-15 00:00:00+00:00
[2025-09-18T00:01:32.916+0000] {standard_task_runner.py:64} INFO - Started process 2842 to run task
[2025-09-18T00:01:32.918+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'espn_news_pipeline', 'dbt_setup', 'scheduled__2025-09-15T00:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/news_pipeline.py', '--cfg-path', '/tmp/tmpgikckjsg']
[2025-09-18T00:01:32.919+0000] {standard_task_runner.py:91} INFO - Job 7: Subtask dbt_setup
[2025-09-18T00:01:32.933+0000] {task_command.py:426} INFO - Running <TaskInstance: espn_news_pipeline.dbt_setup scheduled__2025-09-15T00:00:00+00:00 [running]> on host d90780fea376
[2025-09-18T00:01:32.956+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='espn_news_pipeline' AIRFLOW_CTX_TASK_ID='dbt_setup' AIRFLOW_CTX_EXECUTION_DATE='2025-09-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-15T00:00:00+00:00'
[2025-09-18T00:01:32.956+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-18T00:01:32.960+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-09-18T00:01:32.960+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd $DBT_PROJECT_DIR && /home/airflow/.local/bin/dbt deps']
[2025-09-18T00:01:32.965+0000] {subprocess.py:86} INFO - Output:
[2025-09-18T00:01:32.975+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: /home/airflow/.local/bin/dbt: No such file or directory
[2025-09-18T00:01:32.976+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2025-09-18T00:01:32.976+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-18T00:01:32.979+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2025-09-18T00:01:32.980+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=espn_news_pipeline, task_id=dbt_setup, run_id=scheduled__2025-09-15T00:00:00+00:00, execution_date=20250915T000000, start_date=20250918T000132, end_date=20250918T000132
[2025-09-18T00:01:32.985+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 7 for task dbt_setup (Bash command failed. The command returned a non-zero exit code 127.; 2842)
[2025-09-18T00:01:33.021+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-09-18T00:01:33.029+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-18T00:01:33.031+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-09-20T22:25:07.543+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-20T22:25:07.564+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: espn_news_pipeline.dbt_setup scheduled__2025-09-15T00:00:00+00:00 [queued]>
[2025-09-20T22:25:07.567+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: espn_news_pipeline.dbt_setup scheduled__2025-09-15T00:00:00+00:00 [queued]>
[2025-09-20T22:25:07.567+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-20T22:25:07.573+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_setup> on 2025-09-15 00:00:00+00:00
[2025-09-20T22:25:07.577+0000] {standard_task_runner.py:64} INFO - Started process 75 to run task
[2025-09-20T22:25:07.581+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'espn_news_pipeline', 'dbt_setup', 'scheduled__2025-09-15T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/news_pipeline.py', '--cfg-path', '/tmp/tmp8zr_m1ug']
[2025-09-20T22:25:07.582+0000] {standard_task_runner.py:91} INFO - Job 3: Subtask dbt_setup
[2025-09-20T22:25:07.619+0000] {task_command.py:426} INFO - Running <TaskInstance: espn_news_pipeline.dbt_setup scheduled__2025-09-15T00:00:00+00:00 [running]> on host 27ea88c29fa3
[2025-09-20T22:25:07.656+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='espn_news_pipeline' AIRFLOW_CTX_TASK_ID='dbt_setup' AIRFLOW_CTX_EXECUTION_DATE='2025-09-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-15T00:00:00+00:00'
[2025-09-20T22:25:07.657+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-20T22:25:07.662+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-09-20T22:25:07.663+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd $DBT_PROJECT_DIR && /home/airflow/.local/bin/dbt deps']
[2025-09-20T22:25:07.668+0000] {subprocess.py:86} INFO - Output:
[2025-09-20T22:25:07.669+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: /home/airflow/.local/bin/dbt: No such file or directory
[2025-09-20T22:25:07.669+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2025-09-20T22:25:07.670+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-20T22:25:07.673+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2025-09-20T22:25:07.675+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=espn_news_pipeline, task_id=dbt_setup, run_id=scheduled__2025-09-15T00:00:00+00:00, execution_date=20250915T000000, start_date=20250920T222507, end_date=20250920T222507
[2025-09-20T22:25:07.680+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 3 for task dbt_setup (Bash command failed. The command returned a non-zero exit code 127.; 75)
[2025-09-20T22:25:07.723+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-09-20T22:25:07.731+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-20T22:25:07.734+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
