[2025-09-16T07:12:39.984+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-16T07:12:39.993+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: espn_news_pipeline.dbt_setup scheduled__2025-09-12T00:00:00+00:00 [queued]>
[2025-09-16T07:12:39.995+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: espn_news_pipeline.dbt_setup scheduled__2025-09-12T00:00:00+00:00 [queued]>
[2025-09-16T07:12:39.996+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-16T07:12:40.000+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_setup> on 2025-09-12 00:00:00+00:00
[2025-09-16T07:12:40.002+0000] {standard_task_runner.py:64} INFO - Started process 134 to run task
[2025-09-16T07:12:40.004+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'espn_news_pipeline', 'dbt_setup', 'scheduled__2025-09-12T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/news_pipeline.py', '--cfg-path', '/tmp/tmpcowyspgj']
[2025-09-16T07:12:40.005+0000] {standard_task_runner.py:91} INFO - Job 3: Subtask dbt_setup
[2025-09-16T07:12:40.019+0000] {task_command.py:426} INFO - Running <TaskInstance: espn_news_pipeline.dbt_setup scheduled__2025-09-12T00:00:00+00:00 [running]> on host d90780fea376
[2025-09-16T07:12:40.043+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='espn_news_pipeline' AIRFLOW_CTX_TASK_ID='dbt_setup' AIRFLOW_CTX_EXECUTION_DATE='2025-09-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-12T00:00:00+00:00'
[2025-09-16T07:12:40.043+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-16T07:12:40.048+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-09-16T07:12:40.049+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd $DBT_PROJECT_DIR && /home/airflow/.local/bin/dbt deps']
[2025-09-16T07:12:40.073+0000] {subprocess.py:86} INFO - Output:
[2025-09-16T07:12:40.096+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: /home/airflow/.local/bin/dbt: No such file or directory
[2025-09-16T07:12:40.096+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2025-09-16T07:12:40.096+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-16T07:12:40.100+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2025-09-16T07:12:40.102+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=espn_news_pipeline, task_id=dbt_setup, run_id=scheduled__2025-09-12T00:00:00+00:00, execution_date=20250912T000000, start_date=20250916T071239, end_date=20250916T071240
[2025-09-16T07:12:40.107+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 3 for task dbt_setup (Bash command failed. The command returned a non-zero exit code 127.; 134)
[2025-09-16T07:12:40.148+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-09-16T07:12:40.155+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-16T07:12:40.158+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
